#!/usr/bin/env python3

import click

@click.group()
def qcli():
    pass

@qcli.command()
def start():
    import framework.service
    framework.service.init()

if __name__ == '__main__':
    qcli()
